# -*- coding: utf-8 -*-
"""python course hamnah

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18oYoJbePg7HtB-oLAjsNtjpfYpxqYqpR

This is Hamnahs python tasks file

Task 1 27th December,2024
"""

print("Hello, everyone! I am learning python")

"""Task 2 27th December,2024"""

_1='Hamnah'
_2='11'
_3='Flamingo'

print(_1)
print(_2)
print(_3)

"""Task 28 December ,2024"""

name = 'Nelson Mandela'

print(name,'once said"It always seems impossible until its done" ')

"""Task1   29 December ,2024"""

Favorite_Movie= "Harry Potter"
Birth_year=2013
Price_of_snack= 256
print("Favourite Movie is " +str(Favorite_Movie))
print("fav moive'Favorite_Movie'")
print("My birth year is "+str(Birth_year))
print("My favourite Snack cost is "+str(Price_of_snack))

"""Task 2 29 December,2024"""

hobby = 'diomand painting'

print("My favourite hobby is "+str(hobby))

"""extra challenge 29 December,2024"""

a = 11
b = 6
c = a + b

print(a)
print(b)
print(c)

"""Task 1  .  31 December,2024"""

names=['Isbah','Shezine','Khadija','Ayesha']
for items in names:
  print(items)

"""Task 2 31 December,2024"""

names=['Isbah','Shezine','Khadija','Ayesha']
for items in names:
  print("Welcome to my home " +str(items))

"""Task 3 31 December,2024"""

vehicles = [' Car',' Bike']
for items in vehicles:
  print("I would like to own a" +str(items))

"""Task 4 31 December,2024"""

guests = [' Grandma', ' meternal uncle',' meternal aunt']
for items in guests:
  print("I invite you to a dinner on 16 January, 2025" +str(items))

"""Task 1 3 January,2025"""

alein_colour= 'blue'
if alein_colour=="blue":
  print('you have earned 5 points')

"""Task 2 3 January ,2025"""

alein_colour='blue'
if alein_colour=="green":
  print('you have earned 2 points')
else:
  print('you have earned 10 points')